language: android
jdk: oraclejdk8
dist: trusty

env:
  global:

android:
  components:

  licenses:

before_install:
- yes | sdkmanager "platforms;android-30"

before_script:
  - android-wait-for-emulator
  
