# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# Some code for the file was taken from Wojciech Krzywiec's Medium article:
# https://wkrzywiec.medium.com/github-actions-for-android-first-approach-f616c24aa0f9
# Date Accessed: Nov 24 2020

#ReactiveCircus's Action was used to run an emulator for CI testing
#
# Android Emulator Runner:
# https://github.com/ReactiveCircus/android-emulator-runner

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
      
  instrumenttest:
    runs-on: macos-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Android Emulator Runner
      # You may pin to the exact commit or the version.
      # uses: ReactiveCircus/android-emulator-runner@e08f702234bdc95883c7fd5c7d2867ccf1a8463b
      uses: ReactiveCircus/android-emulator-runner@v2.13.0
      with:
        # API level of the platform and system image - e.g. 23 for Android Marshmallow, 29 for Android 10
        api-level: 29
        target: google_apis
        # custom script to run - e.g. `./gradlew connectedCheck`
        script: ./gradlew connectedCheck --stacktrace
    
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk    
